name: Build and Push Docker Image

# Cand se activeaza robotul?
on:
  push:
    branches: [ "main" ] # Doar cand faci push pe main

jobs:
  build-and-push:
    runs-on: ubuntu-latest # Robotul foloseste un server Ubuntu din cloud-ul lor
    
    steps:
      - name: Descarca codul tau
        uses: actions/checkout@v3

      - name: Logheaza-te in Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construieste si Trimite imaginea (v4)
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: georgevpopa/monitor-siteuri:v4 # Urcam direct versiunea 4
